version: '3.8'

services:
  api:
    build: .
    expose:
      - "8000"
    volumes:
      - ./app:/app/app
    environment:
      - DIFY_API_KEY=${DIFY_API_KEY}
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"  # Changed to 8081 to avoid conflict with Jenkins(8080)
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge