version: '3.8'

services:
  api:
    build: .
    expose:
      - "8000"
    environment:
      - DIFY_API_KEY=${DIFY_API_KEY}
    networks:
      - app_network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge