version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    environment:
      - DIFY_API_KEY=${DIFY_API_KEY}
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"  # Maps container's port 80 to external port 8081 to avoid conflicts
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    restart: unless-stopped
